#! /bin/sh
/usr/bin/xrandr -s 8
pgrep -x sxhkd > /dev/null || sxhkd &

bspc config border_width 0.1
bspc config borderless_monocle   true
bspc config focused_border_color \#a4deff
bspc config normal_border_color \#6272a4
bspc config border_radius 10


bspc monitor -d O O O O O O O O O O
bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

vmware-user-suid-wrapper &
/usr/bin/feh --bg-fill /home/silv/Wallpapers/thunderstorm-sea.png &
~/.config/polybar/./launch.sh &
picom --config ~/.config/picom/picom.conf &
wmname LG3D &
