#! /bin/sh
#/usr/bin/xrandr -s 8
pgrep -x sxhkd > /dev/null || sxhkd & 

bspc config borderless_monocle   true
bspc config focused_border_color \#4b4b4b
bspc config normal_border_color \#2b2b2b

bspc monitor -d O O O O O O O O O O
#bspc config border_radius 10
bspc config border_width 1
bspc config window_gap 12

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off


vmware-user-suid-wrapper &
~/.config/polybar/./launch.sh &
picom --config ~/.config/picom/picom.conf &
wmname LG3D &
