
[global/wm]
margin-bottom = 0
margin-top = 10

;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_

;; File Inclusion
; include an external file, like module file, etc.

include-file = ~/.config/polybar/colors.ini
include-file = ~/.config/polybar/modules.ini
include-file = ~/.config/polybar/user_modules.ini

;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_
 
;; Bar Settings

[bar/primary]

monitor = 
monitor-fallback =
monitor-strict = false
override-redirect = false
wm-restack = bspwm
bottom = false
fixed-center = true

; Dimension defined as pixel value (e.g. 35) or percentage (e.g. 50%),
width = 99%
height = 27

; Offset defined as pixel value (e.g. 35) or percentage (e.g. 50%)
offset-x = 0.5%
offset-y = 1%:-3

; Background ARGB color (e.g. #f00, #ff992a, #ddff1023)
background = ${color.background}

; Foreground ARGB color (e.g. #f00, #ff992a, #ddff1023)
foreground = ${color.foreground}

; Radius
radius-top = 12.0
radius-bottom = 12.0

; Number of spaces to add at the beginning/end of the bar
; Individual side values can be defined using:
;   padding-{left,right}
padding = 0
padding-left = 0

; Number of spaces to add before/after each module
; Individual side values can be defined using:
;   module-margin-{left,right}
module-margin-left = 2
module-margin-right = 2

; Fonts
font-1 = "icomoon\-feather:size=11;2"
font-0 = "Century Gothic:size=11;2"


modules-left = space bspwm
modules-center = title
modules-right =  filesystem cpu memory date network space


separator = " "

dim-value = 1.0
wm-name = 
locale = 
enable-ipc = true
click-left = 
click-middle = 
click-right =
scroll-up =
scroll-down =
double-click-left =
double-click-middle =
double-click-right =
cursor-click = 
cursor-scroll = 

;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_

[settings]

throttle-output = 5
throttle-output-for = 10
throttle-input-for = 30
screenchange-reload = false
compositing-background = source
compositing-foreground = over
compositing-overline = over
compositing-underline = over
compositing-border = over
format-foreground = 
format-background = 
format-underline =
format-overline =
format-spacing =
format-padding =
format-margin =
format-offset =
pseudo-transparency = false
