[module/cpu]
type = internal/cpu
interval = 0.5


format = <label>
format-prefix = 
label = " %percentage%%"

;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_

[module/date]
type = internal/date
interval = 1.0
time = %A  %Y-%m-%d%  %H:%M:%S 
time-alt =  %H:%M:%S     %A
format = <label>
label = %time%

;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_

[module/filesystem]
type = internal/fs
mount-0 = /
interval = 10
fixed-values = true
spacing = 0
format-mounted = <label-mounted>
format-mounted-prefix = " "
format-unmounted = <label-unmounted>
format-unmounted-prefix = 
label-mounted = " %free%"
label-unmounted = %mountpoint%: not mounted

;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_

[module/memory]
type = internal/memory

interval = 3

format = <label>
format-prefix = 
label = " %mb_used%"

;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_

[module/network]
type = internal/network
interface = ens33

content-background = ${color.purple}

content-padding = 3E

; Seconds to sleep between updates

interval = 1.0

accumulate-stats = true

; Consider an `UNKNOWN` interface state as up.
; Some devices have an unknown state, even when they're running
; Default: false
unknown-as-up = true

; Available tags:
;   <label-connected> (default)
;   <ramp-signal>
format-connected = <label-connected>

; Available tags:
;   <label-disconnected> (default)
format-disconnected = <label-disconnected>

; Available tokens:
;   %ifname%    [wireless+wired]
;   %local_ip%  [wireless+wired]
;   %local_ip6% [wireless+wired]
;   %essid%     [wireless]
;   %signal%    [wireless]
;   %upspeed%   [wireless+wired]
;   %downspeed% [wireless+wired]
;   %linkspeed% [wired]
; Default: %ifname% %local_ip%
label-connected = ""

;;label-connected-foreground =rgba(173, 255, 255, 0.98)

; Available tokens:
;   %ifname%    [wireless+wired]
; Default: (none)
label-disconnected = ""
;;label-disconnected-foreground = #66ffffff

; Available tokens:
;   %ifname%    [wireless+wired]
;   %local_ip%  [wireless+wired]
;   %local_ip6% [wireless+wired]
;   %essid%     [wireless]
;   %signal%    [wireless]
;   %upspeed%   [wireless+wired]
;   %downspeed% [wireless+wired]
;   %linkspeed% [wired]
; Default: (none)
;label-packetloss = %essid%
;label-packetloss-foreground = #eefafafa

; Only applies if <ramp-signal> is used
ramp-signal-0 = 
ramp-signal-1 = 
ramp-signal-2 = 
ramp-signal-3 = 
ramp-signal-4 = 



;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-


[module/title]
type = internal/xwindow

; Available tags:
;   <label> (default)
format = <label>
;;format-background = ${color.background}
;;format-padding = 4

; Available tokens:
;   %title%
; Default: %title%
label = %title%
label-foreground = ${color.green}
label-maxlen = 100

; Used instead of label when there is no window title
; Available tokens:
;   None
;;label-empty = Arch Linux
;;label-empty-foreground = #707880

;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_

[module/bspwm]
type = internal/bspwm

#format =  <label-state>

label-focused-foreground = #a4deff
label-focused = •
label-occupied-foreground = #6272a4
label-occupied = • 
label-empty =  •


; Only show workspaces defined on the same output as the bar
; NOTE: The bspwm and XRandR monitor names must match, which they do by default.
; But if you rename your bspwm monitors with bspc -n this option will no longer
; behave correctly.
; Default: true
pin-workspaces = true

inline-mode = false

enable-click = true
enable-scroll = true
reverse-scroll = true

fuzzy-match = false

label-separator = "  "
label-separator-padding = 1

